<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/backend/CompanyHero.Api/CompanyHero.Api.csproj" />
    <ProjectReference Include="../../src/backend/CompanyHero.Migrations/CompanyHero.Migrations.csproj" />
  </ItemGroup>
</Project>
