// <auto-generated />
using System;
using CompanyHero.Modules.Identity.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyHero.Migrations.Migrations.Identity
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.EmailLogin", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.HasKey("TenantId", "PersonId");

                    b.ToTable("email_login", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.ExternalLogin", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_key");

                    b.Property<string>("SubjectHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_hash");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "PersonId");

                    b.ToTable("external_login", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.ExternalProvider", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecretProtected")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_secret_protected");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("external_provider", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.IdentityIndexEntry", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Hash");

                    b.HasIndex("TenantId", "PersonId");

                    b.ToTable("identity_index", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.JoinCode", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("usage_limit");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("join_code", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.KioskCredential", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("KioskId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("kiosk_id");

                    b.Property<string>("PinHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pin_hash");

                    b.Property<DateTimeOffset?>("PinSetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pin_set_at");

                    b.HasKey("TenantId", "PersonId");

                    b.HasIndex("TenantId", "KioskId")
                        .IsUnique();

                    b.ToTable("kiosk_credential", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.KioskDevice", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("LoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("login_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("RegistrationCodeHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("registration_code_hash");

                    b.Property<DateTimeOffset>("RegistrationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("secret_hash");

                    b.Property<DateTimeOffset?>("SecretIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("secret_issued_at");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("RegistrationCodeHash")
                        .IsUnique();

                    b.HasIndex("SecretHash")
                        .IsUnique();

                    b.ToTable("kiosk_device", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.KioskFailedAttempt", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("KioskIdHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kiosk_id_hash");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "DeviceId", "AttemptedAt");

                    b.ToTable("kiosk_failed_attempt", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.LoginPolicy", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.PrimitiveCollection<string[]>("DisabledProviderKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("disabled_provider_keys");

                    b.PrimitiveCollection<string[]>("ForcedProviderKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("forced_provider_keys");

                    b.Property<DateTimeOffset?>("KioskDisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kiosk_disabled_at");

                    b.Property<bool>("KioskEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("kiosk_enabled");

                    b.Property<int>("KioskIdleSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("kiosk_idle_seconds");

                    b.Property<DateTimeOffset?>("MagicLinkDisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("magic_link_disabled_at");

                    b.Property<bool>("MagicLinkEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("magic_link_enabled");

                    b.Property<DateTimeOffset?>("PasskeyDisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("passkey_disabled_at");

                    b.Property<bool>("PasskeyEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("passkey_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId");

                    b.ToTable("login_policy", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.MagicLink", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("magic_link", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.Passkey", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("aaguid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("credential_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sign_count");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("TenantId", "PersonId");

                    b.ToTable("passkey", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.Person", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("RealName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("real_name");

                    b.Property<short>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("state");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "DisplayName")
                        .IsUnique();

                    b.ToTable("person", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.RecoveryCode", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("TenantId", "PersonId");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("recovery_code", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.RoleCode", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid?>("IssuedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("role_code", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AbsoluteUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_until");

                    b.Property<DateTimeOffset>("AuthenticatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authenticated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CsrfToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("csrf_token");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid?>("KioskDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("kiosk_device_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("SlidingUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sliding_until");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "KioskDeviceId");

                    b.HasIndex("TenantId", "PersonId");

                    b.ToTable("session", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.TransferLink", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("transfer_link", "identity");
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.EmailLogin", b =>
                {
                    b.HasOne("CompanyHero.Modules.Identity.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.ExternalLogin", b =>
                {
                    b.HasOne("CompanyHero.Modules.Identity.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.KioskCredential", b =>
                {
                    b.HasOne("CompanyHero.Modules.Identity.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.Passkey", b =>
                {
                    b.HasOne("CompanyHero.Modules.Identity.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyHero.Modules.Identity.Domain.RecoveryCode", b =>
                {
                    b.HasOne("CompanyHero.Modules.Identity.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
