// <auto-generated />
using System;
using CompanyHero.Modules.Entitlements.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyHero.Migrations.Migrations.Entitlements
{
    [DbContext(typeof(EntitlementsDbContext))]
    [Migration("20260926192353_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("entitlements")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyHero.Modules.Entitlements.Domain.Entitlement", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Module")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("module");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from");

                    b.Property<DateTimeOffset?>("ActiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_until");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("TrialUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_until");

                    b.Property<bool>("TrialUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("trial_used");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "Module");

                    b.ToTable("entitlement", "entitlements");
                });

            modelBuilder.Entity("CompanyHero.Modules.Entitlements.Domain.EntitlementHistoryEntry", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorRoles")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_roles");

                    b.Property<short?>("FromState")
                        .HasColumnType("smallint")
                        .HasColumnName("from_state");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("module");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<short>("ToState")
                        .HasColumnType("smallint")
                        .HasColumnName("to_state");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Module", "OccurredAt");

                    b.ToTable("entitlement_history", "entitlements");
                });

            modelBuilder.Entity("CompanyHero.Modules.Entitlements.Domain.TenantLimit", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("TenantId", "Name");

                    b.ToTable("tenant_limit", "entitlements");
                });
#pragma warning restore 612, 618
        }
    }
}
