// <auto-generated />
using System;
using CompanyHero.Modules.Notifications.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyHero.Migrations.Migrations.Notifications
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260926173627_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyHero.Modules.Notifications.Application.ChallengeSnapshot", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<bool>("Ended")
                        .HasColumnType("boolean")
                        .HasColumnName("ended");

                    b.Property<int>("Milestone")
                        .HasColumnType("integer")
                        .HasColumnName("milestone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "ChallengeId");

                    b.ToTable("challenge_snapshot", "notifications");
                });

            modelBuilder.Entity("CompanyHero.Modules.Notifications.Domain.Aushang", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<byte[]>("Pdf")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pdf");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("week");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "GeneratedAt");

                    b.ToTable("aushang", "notifications");
                });

            modelBuilder.Entity("CompanyHero.Modules.Notifications.Domain.Delivery", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dedupe_key");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("Error")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset?>("HeldUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("held_until");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "DedupeKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "PersonId", "Channel", "Day");

                    b.ToTable("delivery", "notifications");
                });

            modelBuilder.Entity("CompanyHero.Modules.Notifications.Domain.NotificationEntry", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("event_key");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("params");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target");

                    b.Property<string>("TextKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("text_key");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "PersonId", "EventKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "PersonId", "OccurredAt");

                    b.ToTable("notification_entry", "notifications");
                });

            modelBuilder.Entity("CompanyHero.Modules.Notifications.Domain.PersonNotificationSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<bool>("EmailChallenge")
                        .HasColumnType("boolean")
                        .HasColumnName("email_challenge");

                    b.Property<int>("EmailFailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("email_failure_count");

                    b.Property<DateTimeOffset?>("EmailPausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_paused_at");

                    b.Property<bool>("EmailProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("email_progress");

                    b.Property<bool>("PushChallenge")
                        .HasColumnType("boolean")
                        .HasColumnName("push_challenge");

                    b.Property<bool>("PushProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("push_progress");

                    b.Property<TimeOnly?>("QuietEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_end");

                    b.Property<TimeOnly?>("QuietStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_start");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "PersonId");

                    b.ToTable("person_settings", "notifications");
                });

            modelBuilder.Entity("CompanyHero.Modules.Notifications.Domain.PushSubscription", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("device_label");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("endpoint");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_count");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("p256dh");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "PersonId");

                    b.ToTable("push_subscription", "notifications");
                });

            modelBuilder.Entity("CompanyHero.Modules.Notifications.Domain.TenantNotificationSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("AushangEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("aushang_enabled");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("email_enabled");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("push_enabled");

                    b.Property<TimeOnly>("QuietEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_end");

                    b.Property<TimeOnly>("QuietStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_start");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId");

                    b.ToTable("tenant_settings", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
