// <auto-generated />
using System;
using CompanyHero.Modules.Metering.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyHero.Migrations.Migrations.Metering
{
    [DbContext(typeof(MeteringDbContext))]
    partial class MeteringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("metering")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyHero.Modules.Metering.Domain.BillingPeriod", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Period")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<byte[]>("ProtectedSalt")
                        .HasColumnType("bytea")
                        .HasColumnName("protected_salt");

                    b.Property<DateTimeOffset?>("SaltDestroyedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("salt_destroyed_at");

                    b.Property<DateTimeOffset?>("SealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sealed_at");

                    b.HasKey("TenantId", "Period");

                    b.ToTable("billing_period", "metering");
                });

            modelBuilder.Entity("CompanyHero.Modules.Metering.Domain.DailyAggregate", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Period")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Module")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("module");

                    b.Property<string>("Metric")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("metric");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<decimal>("RatedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rated_quantity");

                    b.Property<decimal>("UnratedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unrated_quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "Period", "Day", "Module", "Metric");

                    b.ToTable("daily_aggregate", "metering");
                });

            modelBuilder.Entity("CompanyHero.Modules.Metering.Domain.InvoiceDraft", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("Gross")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lines_json");

                    b.Property<decimal>("Net")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("plan_name");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("WouldHaveBeen")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("would_have_been");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Period")
                        .IsUnique();

                    b.ToTable("invoice_draft", "metering");
                });

            modelBuilder.Entity("CompanyHero.Modules.Metering.Domain.LedgerEvent", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("Late")
                        .HasColumnType("boolean")
                        .HasColumnName("late");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("metric");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("module");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<bool>("Rated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("rated");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("ReversalOf")
                        .HasColumnType("uuid")
                        .HasColumnName("reversal_of");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<string>("SubjectRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_ref");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "Period", "Metric");

                    b.ToTable("ledger_event", "metering");
                });

            modelBuilder.Entity("CompanyHero.Modules.Metering.Domain.PricePlanVersion", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_json");

                    b.Property<string>("ValidFromPeriod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("valid_from_period");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "ValidFromPeriod");

                    b.ToTable("price_plan_version", "metering");
                });
#pragma warning restore 612, 618
        }
    }
}
